"""Web-first onboarding wizard.

Phase 3 of the consumer-grade UI overhaul (see plan file
``~/.claude/plans/make-a-plan-for-staged-quasar.md``).

This module owns:

- **State detection** — :func:`wizard_state` walks the current install
  and reports which of three states the /home page should render:
    1. ``needs_setup``    — no ``config/config.json`` yet, or the
                            config's routed models reference API keys
                            that aren't set.
    2. ``no_sessions``    — config OK but no runs have ever landed
                            here. Shows "what do you want to build?"
                            + starter template cards.
    3. ``has_sessions``   — config OK, at least one run in
                            ``log_dir``. Shows the same "build"
                            prompt plus a resume panel.
- **Setup application** — :func:`apply_wizard_choice` writes a
  minimal ``config.json`` from a chosen provider and (optionally)
  persists the API key to ``~/.teane/env.sh`` so future shells
  source it. It never puts secrets inside ``config.json`` — the
  harness architecture already separates secrets via env vars.
- **Starter templates** — :func:`load_starter_templates` reads the
  three JSON descriptors under ``harness/static/templates/`` that
  drive the "no sessions yet — try one of these" cards.

Deliberately no HTTP concerns here. The HTTP handlers live in
:mod:`harness.dashboard`; this module is a plain library so the CLI
wizard could adopt the same building blocks later without pulling in
the dashboard server.
"""

from __future__ import annotations

import json
import logging
import os
import re
import stat
from dataclasses import dataclass
from typing import Any, Optional

logger = logging.getLogger("harness.web_wizard")


# ---------------------------------------------------------------------------
# Provider catalogue
# ---------------------------------------------------------------------------
# Kept in sync with scripts/setup.py's phase-8 defaults. Any new provider
# added to the gateway (harness.gateway._provider_classes) that a hobbyist
# is expected to hit through the web wizard belongs here.

DEFAULT_MODELS_BY_PROVIDER: dict[str, str] = {
    "anthropic": "anthropic:claude-sonnet-4-6",
    "openai":    "openai:gpt-4o-mini",
    "deepseek":  "deepseek:deepseek-v4-flash",
    "moonshot":  "moonshot:kimi-latest",
    "ollama":    "ollama:llama3.2",
}

PROVIDER_ENV_VAR: dict[str, str] = {
    "anthropic": "ANTHROPIC_API_KEY",
    "openai":    "OPENAI_API_KEY",
    "deepseek":  "DEEPSEEK_API_KEY",
    "moonshot":  "MOONSHOT_API_KEY",
    # Ollama runs locally; no key. Kept in the map so the caller can
    # treat every provider uniformly.
    "ollama":    "",
}

# Providers that don't need an API key. Mirrors cli.py:_LOCAL_PROVIDERS.
_LOCAL_PROVIDERS: frozenset[str] = frozenset({"ollama"})


# ---------------------------------------------------------------------------
# Default config builder
# ---------------------------------------------------------------------------

def build_default_config(provider: str, model_key: str) -> dict[str, Any]:
    """Construct a minimal, valid ``config.json`` body for a fresh
    install. Mirrors ``scripts/setup.py:_build_default_config`` — kept
    in-package so the web wizard doesn't have to import the setup
    script (which lives outside the ``harness`` package)."""
    return {
        "_comment": f"Generated by teane web wizard for provider={provider}",
        "model_routing": {
            "planning_primary":   model_key,
            "planning_mode":      "thinking_max",
            "planning_fallback":  "",
            "patching_primary":   model_key,
            "patching_mode":      "non_thinking",
            "repair_primary":     model_key,
            "repair_fallback":    "",
            "repair_mode":        "thinking",
            "doc_reviewer_primary":  "",
            "doc_reviewer_mode":     "thinking",
            "doc_reviewer_fallback": "",
            "code_reviewer_primary":  "",
            "code_reviewer_mode":     "thinking",
            "code_reviewer_fallback": "",
        },
        "node_throttle": {
            "_comment": (
                "Per-loop hard ceilings. Clamped to [0,5] at config load; "
                "0 suspends the loop without clearing the model slot."
            ),
            "max_patch_repair_iterations": 3,
            "max_doc_review_cycles":       1,
            "max_code_review_cycles":      1,
            "max_discovery_iterations":    10,
        },
    }


# ---------------------------------------------------------------------------
# State detection
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class WizardState:
    """The three-way rendering signal for the Home page.

    ``kind`` is one of ``needs_setup`` / ``no_sessions`` / ``has_sessions``.
    All other fields are informational — they let the renderer show
    contextual help (e.g. which providers already have a key set).
    """

    kind: str
    config_path: str
    has_config: bool
    missing_env_vars: tuple[str, ...] = ()
    providers_with_key_set: tuple[str, ...] = ()
    session_count: int = 0
    log_dir: str = ""


def _providers_with_key_set() -> tuple[str, ...]:
    """Which of the four known providers currently have their env var
    populated in this process. Used to prefer the already-configured
    provider when auto-picking the wizard's default choice."""
    have: list[str] = []
    for provider, env_var in PROVIDER_ENV_VAR.items():
        if not env_var:  # local provider, always "available"
            have.append(provider)
            continue
        if os.environ.get(env_var, "").strip():
            have.append(provider)
    return tuple(have)


def wizard_state(dashboard_cfg: Any) -> WizardState:
    """Compute the state the Home page should render.

    Never raises. If any subsystem probe fails we degrade to
    ``needs_setup`` so the page prompts the operator to fix things,
    rather than crashing before they see the wizard.
    """
    # Import lazily so a broken cli import doesn't take down the
    # whole dashboard module at load time.
    try:
        from harness.cli import (  # type: ignore
            _get_global_config_path,
            discover_config,
            find_missing_api_keys,
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("[wizard] cli import failed: %s", exc)
        return WizardState(
            kind="needs_setup",
            config_path="",
            has_config=False,
            providers_with_key_set=_providers_with_key_set(),
        )

    config_path = _get_global_config_path()
    log_dir = os.path.expanduser(getattr(dashboard_cfg, "log_dir", "") or "")

    has_config = os.path.isfile(config_path)
    missing: dict[str, list[str]] = {}
    if has_config:
        try:
            cfg_dict = discover_config(None)
            missing = find_missing_api_keys(cfg_dict) or {}
        except Exception as exc:  # noqa: BLE001
            # Malformed config or missing required fields — treat as
            # needing setup so the wizard shows.
            logger.info("[wizard] config load failed, needs setup: %s", exc)
            return WizardState(
                kind="needs_setup",
                config_path=config_path,
                has_config=False,
                providers_with_key_set=_providers_with_key_set(),
            )

    session_count = 0
    if log_dir and os.path.isdir(log_dir):
        try:
            from harness.metrics import list_sessions
            session_count = len(list_sessions(log_dir))
        except Exception as exc:  # noqa: BLE001
            logger.warning("[wizard] list_sessions failed: %s", exc)

    missing_env = tuple(sorted(missing.keys()))
    if not has_config or missing_env:
        return WizardState(
            kind="needs_setup",
            config_path=config_path,
            has_config=has_config,
            missing_env_vars=missing_env,
            providers_with_key_set=_providers_with_key_set(),
            session_count=session_count,
            log_dir=log_dir,
        )

    kind = "has_sessions" if session_count > 0 else "no_sessions"
    return WizardState(
        kind=kind,
        config_path=config_path,
        has_config=True,
        providers_with_key_set=_providers_with_key_set(),
        session_count=session_count,
        log_dir=log_dir,
    )


# ---------------------------------------------------------------------------
# Setup application — write config + env file
# ---------------------------------------------------------------------------

_TEANE_HOME_DIR_ENV = "TEANE_HOME"


def _teane_home_dir() -> str:
    """Resolve the ~/.teane directory (or ``$TEANE_HOME`` override).
    Used only for the wizard's env-var sidecar; the harness itself
    still uses ``~/.harness/`` for its state (see [[project_teane_brand]])."""
    override = os.environ.get(_TEANE_HOME_DIR_ENV, "").strip()
    if override:
        return os.path.expanduser(override)
    return os.path.expanduser(os.path.join("~", ".teane"))


_ENV_KEY_SAFE = re.compile(r"^[A-Z][A-Z0-9_]*$")
_ENV_VAL_UNSAFE = re.compile(r"[\r\n\x00]")


def _validate_env_pair(name: str, value: str) -> None:
    """Refuse env-var names/values that would break a sourceable
    ``env.sh``. Names must be shell-legal; values must not contain
    control characters that could smuggle extra statements past the
    single-quote escape."""
    if not _ENV_KEY_SAFE.match(name):
        raise ValueError(f"unsafe env var name: {name!r}")
    if _ENV_VAL_UNSAFE.search(value):
        raise ValueError("env var value contains a control character")


def write_env_sh(pairs: dict[str, str], *, dest: Optional[str] = None) -> str:
    """Write a sourceable shell env file at ``~/.teane/env.sh`` (or
    ``dest``). Uses ``export VAR='value'`` with the value single-quoted
    and single quotes escaped POSIX-portably (``'\\''``).

    Overwrites existing values for the given keys; leaves any other
    exports in the file untouched so a user who has hand-tuned the
    file doesn't lose their changes.

    Sets mode 0600 (owner-read/write only) — the file may contain
    API keys.

    Returns the absolute path written.
    """
    if not pairs:
        return ""
    for name, value in pairs.items():
        _validate_env_pair(name, str(value))
    path = os.path.abspath(dest) if dest else os.path.join(_teane_home_dir(), "env.sh")
    os.makedirs(os.path.dirname(path), exist_ok=True)

    existing_lines: list[str] = []
    if os.path.isfile(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                existing_lines = f.read().splitlines()
        except OSError:
            existing_lines = []

    def _fmt(name: str, value: str) -> str:
        escaped = str(value).replace("'", "'\\''")
        return f"export {name}='{escaped}'"

    seen: set[str] = set()
    out: list[str] = []
    export_re = re.compile(r"^\s*export\s+([A-Z][A-Z0-9_]*)=")
    for line in existing_lines:
        m = export_re.match(line)
        if m and m.group(1) in pairs:
            out.append(_fmt(m.group(1), pairs[m.group(1)]))
            seen.add(m.group(1))
        else:
            out.append(line)
    # Header if this is a fresh file.
    if not existing_lines:
        out.append("# Generated by teane web wizard. `source ~/.teane/env.sh`")
        out.append("# to make API keys available to the CLI. Regenerate any time.")
    for name, value in pairs.items():
        if name in seen:
            continue
        out.append(_fmt(name, value))

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out).rstrip("\n") + "\n")
    try:
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass
    return path


@dataclass
class ApplyResult:
    """What :func:`apply_wizard_choice` did (or refused to do)."""

    ok: bool
    config_path: str = ""
    env_sh_path: str = ""
    error: str = ""


def apply_wizard_choice(
    *,
    provider: str,
    api_key: str,
    dashboard_cfg: Any,
    dest_config_path: Optional[str] = None,
    dest_env_sh_path: Optional[str] = None,
    validate: bool = True,
) -> ApplyResult:
    """Write a fresh ``config.json`` for ``provider`` and (for remote
    providers) persist ``api_key`` to ``~/.teane/env.sh``.

    Does NOT put the key inside ``config.json``. The harness's config
    validation resolves secrets from env vars; keeping them in a
    sidecar means the config can be checked into a private repo
    without leaking credentials.

    Validation is optional so tests can exercise the write path
    without importing the full harness config validator; production
    callers should leave it on.
    """
    from harness.cli import _get_global_config_path  # local import

    provider = (provider or "").strip().lower()
    if provider not in DEFAULT_MODELS_BY_PROVIDER:
        return ApplyResult(
            ok=False,
            error=(
                f"unknown provider {provider!r}; "
                f"pick one of {sorted(DEFAULT_MODELS_BY_PROVIDER)}"
            ),
        )
    if provider not in _LOCAL_PROVIDERS and not (api_key or "").strip():
        return ApplyResult(
            ok=False,
            error=f"{PROVIDER_ENV_VAR[provider]} is required for {provider}",
        )

    model_key = DEFAULT_MODELS_BY_PROVIDER[provider]
    config = build_default_config(provider, model_key)

    # Persist the API key first — the config validator will insist the
    # key be resolvable when it runs.
    env_sh_path = ""
    if provider not in _LOCAL_PROVIDERS:
        env_var = PROVIDER_ENV_VAR[provider]
        os.environ[env_var] = api_key
        try:
            env_sh_path = write_env_sh(
                {env_var: api_key},
                dest=dest_env_sh_path,
            )
        except ValueError as exc:
            return ApplyResult(ok=False, error=str(exc))
        except OSError as exc:
            return ApplyResult(
                ok=False,
                error=f"could not write env sidecar: {exc}",
            )

    config_path = os.path.abspath(dest_config_path) if dest_config_path else _get_global_config_path()
    os.makedirs(os.path.dirname(config_path), exist_ok=True)
    tmp = config_path + ".tmp"
    try:
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2, sort_keys=False)
            f.write("\n")
        os.replace(tmp, config_path)
    except OSError as exc:
        return ApplyResult(ok=False, error=f"config write failed: {exc}")

    if validate:
        try:
            from harness.cli import validate_config_strict
            validate_config_strict(config, source=config_path)
        except Exception as exc:  # noqa: BLE001
            return ApplyResult(
                ok=False,
                config_path=config_path,
                env_sh_path=env_sh_path,
                error=f"generated config failed strict validation: {exc}",
            )

    return ApplyResult(
        ok=True,
        config_path=config_path,
        env_sh_path=env_sh_path,
    )


# ---------------------------------------------------------------------------
# Starter templates
# ---------------------------------------------------------------------------

_TEMPLATES_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "static", "templates"
)


@dataclass(frozen=True)
class StarterTemplate:
    """One entry on the 'no sessions yet — try one of these' page."""

    slug: str
    title: str
    description: str
    prompt: str
    suggested_workspace: str = ""


def load_starter_templates(*, templates_dir: Optional[str] = None) -> list[StarterTemplate]:
    """Load every ``starter-*.json`` descriptor. Sorted by title so
    the page order is deterministic."""
    root = templates_dir or _TEMPLATES_DIR
    if not os.path.isdir(root):
        return []
    out: list[StarterTemplate] = []
    for entry in sorted(os.listdir(root)):
        if not entry.startswith("starter-") or not entry.endswith(".json"):
            continue
        path = os.path.join(root, entry)
        try:
            with open(path, "r", encoding="utf-8") as f:
                raw = json.load(f)
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning("[wizard] skipping bad template %s: %s", entry, exc)
            continue
        if not isinstance(raw, dict):
            continue
        slug = entry.removeprefix("starter-").removesuffix(".json")
        try:
            out.append(StarterTemplate(
                slug=slug,
                title=str(raw.get("title", slug)),
                description=str(raw.get("description", "")),
                prompt=str(raw.get("prompt", "")),
                suggested_workspace=str(raw.get("suggested_workspace", "")),
            ))
        except Exception as exc:  # noqa: BLE001
            logger.warning("[wizard] skipping malformed template %s: %s", entry, exc)
    out.sort(key=lambda t: t.title)
    return out
